# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('data_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTypeConsumptionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('interval_start', models.DateTimeField()),
                ('interval', models.DurationField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.ProfileType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
