# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pfc', '0006_pfcmarketconsumptionrecord'),
        ('companies', '0005_auto_20180111_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget_report', models.FileField(blank=True, null=True, upload_to=b'')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('cc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_budget', to='companies.Meter')),
                ('pfc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfc_budget', to='pfc.PFC')),
                ('pfc_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfc_market_budget', to='pfc.PFCMarket')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('interval_start', models.DateTimeField()),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='budget.Budget')),
            ],
            options={
                'ordering': ('-interval_start',),
            },
        ),
    ]
