# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20180111_1403'),
        ('budget', '0002_budgetrecord_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_site', to='companies.Site'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
