# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20171229_1410'),
        ('budget', '0006_auto_20180117_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSeasonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('interval_start', models.DateTimeField()),
                ('interval', models.DurationField(null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_season', to='budget.Budget')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_schedule', to='core.Shedule')),
            ],
            options={
                'ordering': ('-interval_start',),
            },
        ),
    ]
