# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budgetseasonrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
