# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_budget_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='pfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfc_budget', to='pfc.PFC'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='pfc_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfc_market_budget', to='pfc.PFCMarket'),
        ),
    ]
