# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_budgetrecord_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetseasonrecord',
            options={'ordering': ('-pk',)},
        ),
        migrations.RemoveField(
            model_name='budgetseasonrecord',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='budgetseasonrecord',
            name='interval_start',
        ),
    ]
