# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20180129_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetseasonrecord',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
