# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180228_1603'),
        ('budget', '0014_weightedaveragerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetWeeklyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_weekly', to='budget.Budget')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='core.Shedule')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
