# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_budgetweeklyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetweeklyrecord',
            name='season',
        ),
    ]
