# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20180306_0931'),
        ('budget', '0018_budgetmedrecord_budgetmedwithriscsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMedSeasonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_season_med', to='budget.Budget')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_season_med_season_schedule', to='core.Shedule')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetMedSeasonWithRiscsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_season_med_riscs', to='budget.Budget')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_season_med_riscs_season_schedule', to='core.Shedule')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
