# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_budgetaverageperyear_budgetaverageperyearriscs'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='lissage',
            field=models.BooleanField(default=False),
        ),
    ]
