# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_budgetaveragemajorationperyear_budgetmedseasonmajorationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetaveragemajorationperyear',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetaverageperyear',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetaverageperyearriscs',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetaveragewithoutefort',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmedrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmedseasonmajorationrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmedseasonrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmedseasonwithriscsrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmedwithriscsrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetseasonrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightedaveragerecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
