# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfc_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='PfcConsumptionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data_file', models.FileField(upload_to=b'')),
                ('pfc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfc.PFC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PfcConsumptionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('interval_start', models.DateTimeField()),
                ('interval', models.DurationField()),
                ('from_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.PfcConsumptionFile')),
                ('pfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.PFC')),
            ],
            options={
                'ordering': ('-interval_start',),
            },
        ),
    ]
