# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0002_pfc_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfc_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('market', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='pfc',
            name='market',
        ),
    ]
