# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0003_auto_20180109_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfcmarket',
            name='market',
        ),
    ]
