# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0004_remove_pfcmarket_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcconsumptionfile',
            name='pfc_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfc.PFCMarket'),
        ),
    ]
