# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0006_pfcmarketconsumptionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfcconsumptionrecord',
            name='from_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfc.PfcConsumptionFile'),
        ),
        migrations.AlterField(
            model_name='pfcmarketconsumptionrecord',
            name='from_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfc.PfcConsumptionFile'),
        ),
    ]
