# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0008_auto_20180518_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfc',
            name='eco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pfc',
            name='risc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
