# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0011_auto_20180808_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfcmarket',
            name='custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
