# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pfc', '0012_pfcmarket_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PfcPeakRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('peak', models.CharField(blank=True, choices=[('peak', 'Peak'), ('base', 'Base')], max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('pfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc.PFC')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
