# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='holiday',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
    ]
