# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20161201_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='month',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 12, 2, 12, 9, 45, 431025, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
