# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20161202_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='holidays',
            field=models.ManyToManyField(to='geo.Holiday'),
        ),
    ]
