# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161115_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='weekday',
        ),
        migrations.AddField(
            model_name='daypattern',
            name='hours',
            field=models.ManyToManyField(blank=True, to='core.Hour'),
        ),
    ]
