# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('core', '0006_energyconsumptionreport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumptionfile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='exclude_holidays',
            field=models.BooleanField(default=False),
        ),
    ]
