# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0008_auto_20161201_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumptionreport',
            name='exclude_holidays',
        ),
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='meter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Meter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='meter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Meter'),
            preserve_default=False,
        ),
    ]
