# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20161201_1038'),
        ('core', '0009_auto_20161201_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumptionfile',
            name='location',
        ),
        migrations.AddField(
            model_name='energyconsumptionfile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Site'),
        ),
    ]
