# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161201_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumptionrecord',
            name='location',
        ),
    ]
