# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161201_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyconsumptionrecord',
            options={'ordering': ('-interval_start',)},
        ),
    ]
