# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170322_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='time_peak',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='time_peakof',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
