# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170512_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyconsumptionreport',
            old_name='time_peakof',
            new_name='time_peakoff',
        ),
    ]
