# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shedule',
            name='months',
            field=models.ManyToManyField(blank=True, to='core.Month'),
        ),
    ]
