# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20161202_1209'),
        ('core', '0019_auto_20170731_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
            preserve_default=False,
        ),
    ]
