# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shedule_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='months',
            options={'verbose_name_plural': 'Months'},
        ),
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='shedules',
            field=models.ManyToManyField(related_name='shedules', to='core.Shedule'),
        ),
    ]
