# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170801_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Weekdays',
            },
        ),
    ]
