# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170802_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'ordering': ('-value',)},
        ),
    ]
