# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170807_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
