# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_shedule_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='all_holidays',
            field=models.BooleanField(default=False),
        ),
    ]
