# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170816_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='off_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
