# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0029_shedule_off_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetConsumptionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('time_peak', models.TimeField(blank=True, null=True)),
                ('time_peakoff', models.TimeField(blank=True, null=True)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('budget_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('budget_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_meter', to='companies.Meter')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='companies.Meter')),
                ('shedules', models.ManyToManyField(related_name='budget_shedules', to='core.Shedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
