# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0030_budgetconsumptionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetconsumptionreport',
            name='meter',
        ),
        migrations.AddField(
            model_name='budgetconsumptionreport',
            name='pmeter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pmeter', to='companies.Meter'),
            preserve_default=False,
        ),
    ]
