# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0033_budgetconsumptionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetconsumptionreport',
            name='pmeter',
        ),
        migrations.RemoveField(
            model_name='budgetconsumptionreport',
            name='budget_meter',
        ),
        migrations.AddField(
            model_name='budgetconsumptionreport',
            name='budget_meter',
            field=models.ManyToManyField(related_name='budget_meter', to='companies.Meter'),
        ),
    ]
