# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0034_auto_20170824_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconsumptionreport',
            name='meters',
            field=models.ManyToManyField(null=True, related_name='meters', to='companies.Meter'),
        ),
        migrations.AlterField(
            model_name='budgetconsumptionreport',
            name='budget_meter',
            field=models.ManyToManyField(null=True, related_name='budget_meter', to='companies.Meter'),
        ),
    ]
