# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0038_auto_20170824_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetreport',
            name='meters',
        ),
        migrations.AddField(
            model_name='budgetreport',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='companies.Meter'),
        ),
    ]
