# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170824_1403'),
        ('core', '0039_auto_20170824_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('year', models.TimeField()),
                ('translation_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_meter', to='companies.Meter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
