# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170825_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrecords',
            name='translated_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='translationrecords',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
