# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20170825_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumptionreport',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
