# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_sumdiffreport_meter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumdiffreport',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
