# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_budgetreport_self_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumdiffreport',
            name='diff_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sumdiffreport',
            name='diff_cc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
