# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20170918_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumdiffreport',
            name='diff_cc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
