# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_energyconsumptionfile_multi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetreport',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetreport',
            name='shedules',
        ),
        migrations.RemoveField(
            model_name='sumdiffreport',
            name='meters',
        ),
        migrations.RemoveField(
            model_name='sumdiffreport',
            name='shedules',
        ),
        migrations.RemoveField(
            model_name='translationrecords',
            name='translation_meter',
        ),
        migrations.DeleteModel(
            name='BudgetReport',
        ),
        migrations.DeleteModel(
            name='SumDiffReport',
        ),
        migrations.DeleteModel(
            name='TranslationRecords',
        ),
    ]
