# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180123_1616'),
        ('core', '0054_auto_20180223_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('time_peak', models.TimeField(blank=True, null=True)),
                ('time_peakoff', models.TimeField(blank=True, null=True)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('budget_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('pfc', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('self_unit', models.CharField(blank=True, max_length=255)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='companies.Meter')),
                ('shedules', models.ManyToManyField(related_name='budget_shedules', to='core.Shedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SumDiffReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('meter_name', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('diff_bool', models.BooleanField(default=False)),
                ('diff_cc', models.IntegerField(blank=True, default=0, null=True)),
                ('meters', models.ManyToManyField(blank=True, related_name='meters', to='companies.Meter')),
                ('shedules', models.ManyToManyField(related_name='sum_shedules', to='core.Shedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('translation_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_meter', to='companies.Meter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
