# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180228_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumptionrecord',
            name='from_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EnergyConsumptionFile'),
        ),
    ]
