# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20180306_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumptionfile',
            name='sum_file',
            field=models.BooleanField(default=False),
        ),
    ]
