# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0052_energyconsumptionfile_meters'),
        ('companies', '0007_auto_20180123_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('years', models.CharField(blank=True, max_length=100)),
                ('cc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_translation', to='companies.Meter')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('interval_start', models.DateTimeField()),
                ('interval', models.DurationField()),
                ('from_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EnergyConsumptionFile')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Meter')),
            ],
            options={
                'ordering': ('-interval_start',),
            },
        ),
    ]
