# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 08:02
from __future__ import unicode_literals

from django.db import migrations, models


def load_stores(apps, schema_editor):
    Cockpit = apps.get_model("cockpit", "Cockpit")
    cockpit1_corporate = Cockpit(id=1, name='Envoi signalé')
    cockpit1_corporate.save()

    cockpit2_corporate = Cockpit(id=2, name='Hebdomadaire')
    cockpit2_corporate.save()

    cockpit3_corporate = Cockpit(id=3, name='Mensuel (1er jour ouvrier du mois)')
    cockpit3_corporate.save()


def delete_stores(apps, schema_editor):
    Cockpit = apps.get_model("cockpit", "Cockpit")
    Cockpit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_stores), 
        ]

