# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0003_auto_20180430_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitoffer',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
