# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_headgerecord_schedule'),
        ('cockpit', '0005_auto_20180502_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitoffer',
            name='weekday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Weekday'),
        ),
    ]
