# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0009_auto_20180822_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cockpit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cockpit.CockpitNews')),
            ],
        ),
        migrations.RemoveField(
            model_name='cockpitmarket',
            name='cockpit',
        ),
        migrations.AddField(
            model_name='cockpitmarket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cockpit.NewsCategory'),
        ),
        migrations.AddField(
            model_name='cockpitmarket',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cockpit.Chart'),
        ),
    ]
