# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0010_auto_20180824_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitmarket',
            name='market_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
