# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0011_cockpitmarket_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitoffer',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
