# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0012_cockpitoffer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cockpitoffer',
            name='value',
        ),
    ]
