# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_headgerecord_schedule'),
        ('cockpit', '0014_auto_20181120_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitnews',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cockpitnews',
            name='weekdays',
            field=models.ManyToManyField(blank=True, null=True, to='core.Weekday'),
        ),
    ]
