# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0015_auto_20181127_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'cockpit/'),
        ),
    ]
