# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0016_chart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitnews',
            name='month',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cockpitnews',
            name='weekdays',
            field=models.ManyToManyField(blank=True, to='core.Weekday'),
        ),
    ]
