# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0051_auto_20171229_1410'),
        ('companies', '0005_auto_20180111_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('consumption', models.CharField(blank=True, max_length=100)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('employees', models.CharField(blank=True, choices=[('to_10', 'From 1 to 10'), ('to_50', 'From 11 to 50'), ('to_100', 'From 51 to 100'), ('more_than_100', 'More than 100')], max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('weekdays', models.ManyToManyField(related_name='offer_weekdays', to='core.Weekday')),
            ],
        ),
    ]
