# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('offers', '0002_auto_20180119_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='profile',
            field=models.ManyToManyField(related_name='offer_profile', to='type.ProfileType'),
        ),
    ]
