# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20180119_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='years',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
