# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='datetime_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='datetime_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
