# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180123_1616'),
        ('offers', '0006_auto_20180129_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='offer',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_cc', to='companies.Meter'),
        ),
    ]
