# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20180130_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(upload_to=b'plots/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
