# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_budgetreport_sumdiffreport_translationrecords'),
        ('offers', '0014_auto_20180227_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riscrecords',
            name='risc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='riscs',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='shedules',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='unique_prix',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='validation_time',
        ),
        migrations.AddField(
            model_name='offer',
            name='weekdays',
            field=models.ManyToManyField(blank=True, related_name='offer_weekdays', to='core.Weekday'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_pfc', to='pfc.PFC'),
        ),
        migrations.DeleteModel(
            name='Risc',
        ),
        migrations.DeleteModel(
            name='RiscRecords',
        ),
    ]
