# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180228_1603'),
        ('offers', '0015_auto_20180228_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='RiscRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('risc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risc', to='offers.Risc')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(blank=True, choices=[(b'Standart', b'Standart'), (b'SME', b'SME')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='shedules',
            field=models.ManyToManyField(blank=True, related_name='offer_shedules', to='core.Shedule'),
        ),
        migrations.AddField(
            model_name='offer',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='validation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='riscs',
            field=models.ManyToManyField(blank=True, related_name='offer_riscs', to='offers.Risc'),
        ),
    ]
