# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_auto_20180228_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='riscrecord',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
