# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20180326_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(blank=True, choices=[(b'indicative', b'Offre indicative'), (b'signer', b'Offre A signer'), (b'signee', b'Offre signee'), (b'supprimer', b'A supprimer')], max_length=255, null=True),
        ),
    ]
