# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_auto_20180405_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterrecord',
            name='final',
            field=models.BooleanField(default=True),
        ),
    ]
