# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0027_parameterrecord_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterrecord',
            name='final',
        ),
        migrations.AddField(
            model_name='parameter',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
