# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0029_offer_lissage_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='second_type',
            field=models.CharField(blank=True, choices=[(b'prolongation', b'Prolongation'), (b'acquisition', b'Acquisition'), (b'retention', b'Retention')], max_length=255, null=True),
        ),
    ]
