# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typepondere', '0001_initial'),
        ('offers', '0030_offer_second_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='profile_pondere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_pondere', to='typepondere.ProfileTypePondere'),
        ),
    ]
