# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0031_offer_profile_pondere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='lissage_years',
            field=models.TextField(blank=True),
        ),
    ]
