# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models

def load_stores(apps, schema_editor):
    Constants = apps.get_model("offers", "Constants")
    constants_corporate = Constants(id=1, name='Marges Max')
    constants_corporate.save()

    constants2_corporate = Constants(id=2, name='Marges Min')
    constants2_corporate.save()

    constants3_corporate = Constants(id=3, name='Lissage')
    constants3_corporate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0033_constants'),
    ]

    operations = [
	    migrations.RunPython(load_stores),
    ]
