# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_auto_20180502_0939'),
    ]

    operations = [

    ]
