# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0035_auto_20180503_0958'),
    ]

    operations = [

    ]
