# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20180503_0907'),
        ('offers', '0038_auto_20180503_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='offer',
            name='unsigned_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_user', to='client.Profile'),
        ),
    ]
