# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0039_auto_20180504_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
