# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0040_auto_20180504_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mail_valid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
