# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0041_offer_mail_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mail_valid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
