# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0043_auto_20180504_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='token',
        ),
    ]
