# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0045_offer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
