# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0046_auto_20180504_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='signed_years',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
