# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0048_offer_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='eligibilite',
            field=models.FileField(blank=True, null=True, upload_to=b'eligibilite/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to=b'signed/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='unsigned_file',
            field=models.FileField(blank=True, null=True, upload_to=b'unsigned/'),
        ),
    ]
