# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0049_auto_20180516_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
