# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0050_offer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='energy_type',
            field=models.CharField(blank=True, choices=[('nuclear', 'GO Nucl\xe9aire'), ('hydraulic', 'GO Hydraulique'), ('naturemade_star', 'GO Naturemade star')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='opportunite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
