# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0052_auto_20180517_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='nr_opportunite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
