# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0053_offer_nr_opportunite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne1', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne2', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne3', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne4', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne5', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne6', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne7', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne8', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='GRDFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data_file', models.FileField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
