# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0054_grd_grdfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='grd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_grd', to='offers.GRD'),
        ),
    ]
