# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models

def load_stores(apps, schema_editor):
    Constants = apps.get_model("offers", "Constants")
    constants_corporate = Constants(id=4, name='Duree')
    constants_corporate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0055_offer_grd'),
    ]

    operations = [
	migrations.RunPython(load_stores),
    ]
