# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0056_auto_20180521_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='marche',
            field=models.BooleanField(default=False),
        ),
    ]
