# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0057_offer_marche'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='releve',
            field=models.BooleanField(default=False),
        ),
    ]
