# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0058_offer_releve'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
