# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0060_auto_20180525_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
    ]
