# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0061_offer_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='eligible',
        ),
    ]
