# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0063_auto_20180606_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='opportunite',
        ),
        migrations.AddField(
            model_name='offer',
            name='sme_status',
            field=models.CharField(blank=True, choices=[('pending', 'En cours'), ('ferme', 'Ferme'), ('indicative', 'Offre indicative'), ('signer', 'Offre A signer'), ('signee', 'Offre signee'), ('supprimer', 'A supprimer')], default='indicative', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('pending', 'En cours'), ('ferme', 'Ferme'), ('indicative', 'Offre indicative'), ('signer', 'Offre A signer'), ('signee', 'Offre signee'), ('supprimer', 'A supprimer')], default='indicative', max_length=255, null=True),
        ),
    ]
