# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-08 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0064_auto_20180606_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='conseiller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_conseiller_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
