# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0065_offer_conseiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='emails',
            field=models.TextField(blank=True),
        ),
    ]
