# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0067_auto_20180619_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='signatures',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
