# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0068_offer_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='signatures',
            field=models.ManyToManyField(blank=True, to='client.Profile'),
        ),
    ]
