# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0069_auto_20180709_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='signatures',
        ),
    ]
