# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20180709_1712'),
        ('offers', '0070_remove_offer_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='signatures',
            field=models.ManyToManyField(blank=True, to='client.Profile'),
        ),
    ]
