# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0074_auto_20180710_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='signed_years',
            new_name='lis_years',
        ),
        migrations.AddField(
            model_name='offer',
            name='marge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='volumetrie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
