# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0075_auto_20180710_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
