# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0076_offer_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lis_force',
            field=models.BooleanField(default=False),
        ),
    ]
