# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0077_offer_lis_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('pending', 'En cours'), ('confirmer', 'A Confirmer'), ('ferme', 'Ferme'), ('indicative', 'Prix indicatifs'), ('signer', 'Offre A signer'), ('signee', 'Offre signee'), ('supprimer', 'A supprimer')], default='indicative', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sme_status',
            field=models.CharField(blank=True, choices=[('pending', 'En cours'), ('confirmer', 'A Confirmer'), ('ferme', 'Ferme'), ('indicative', 'Prix indicatifs'), ('signer', 'Offre A signer'), ('signee', 'Offre signee'), ('supprimer', 'A supprimer')], default='indicative', max_length=255, null=True),
        ),
    ]
