# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0080_auto_20180717_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='riscrecord',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
