# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0081_riscrecord_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='riscrecord',
            name='rid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riscrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
