# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0082_auto_20180731_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='lissage_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='status_lisse',
            field=models.BooleanField(default=False),
        ),
    ]
