# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 11:25
from __future__ import unicode_literals

from django.db import migrations


# def load_stores(apps, schema_editor):
#     Constants = apps.get_model("offers", "Constants")
#     constants_corporate5 = Constants(id=5, name='max_volume_cc')
#     constants_corporate5.save()

class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0083_auto_20180814_1418'),
    ]

    operations = [
	    # migrations.RunPython(load_stores),
    ]
