# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0088_offer_lis_manual_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
