# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0090_offer_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pfc_date_first',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pfc_date_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
