# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0091_auto_20180911_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='signee_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
