# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0092_offer_signee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risc',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
