# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20161201_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ('-pk',)},
        ),
    ]
