# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20170731_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('-pk',)},
        ),
    ]
