# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20180111_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
    ]
