# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_meter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_sum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='multisite',
            field=models.BooleanField(default=False),
        ),
    ]
