# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20180319_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
