# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_site_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
