# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_meter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crm_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
