# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nom_entrepise',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
