# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_nom_entrepise'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Madame'), ('M', 'Monsieur')], max_length=1, null=True),
        ),
    ]
