# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='format_donnees',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
