# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_holidayfile'),
        ('offers', '0080_auto_20180717_1255'),
        ('companies', '0018_auto_20180705_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('log_type', models.CharField(blank=True, choices=[('open', 'Open Offer Email'), ('click', 'Click Offer Email'), ('send', 'Offer Send Email')], max_length=1, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
        ),
    ]
