# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0022_auto_20180725_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_client_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
