# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_clientlog_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
