# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20180730_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlog',
            name='device',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='desktop', max_length=100, null=True),
        ),
    ]
