# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_auto_20180807_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
