# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Admin'), (2, b'Client')], default=2, null=True),
        ),
    ]
