# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180125_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Admin'), (2, b'Client')], null=True),
        ),
    ]
