# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
