# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_profile_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='code',
        ),
    ]
