# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20180528_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[(b'F', b'Madame'), (b'M', b'Monsieur')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to=b'signatures/'),
        ),
    ]
