# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20180709_1712'),
        ('client', '0016_auto_20180710_1447'),
    ]

    operations = [
    ]
