# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_merge_20180710_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
