# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_profile_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temp',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
