# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_log',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
