# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20180726_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
