# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_profile_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='per_pag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
