# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_auto_20180907_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_auth',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
