# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20180910_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fonction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Account Manager'), (2, 'Responsable March\xe9s'), (3, 'Directeur'), (4, 'CEO'), (5, 'Custom')], default=2, null=True),
        ),
    ]
